export const DEFAULT_HOME_DATA = {
  ticker: {
    enabled: true,
    items: [
      'Next-Gen Enterprise Security & CCTV Surveillance',
      'Advanced Biometric Access Control & Mantrap Portals',
      'Unified PSIM Command & Telemetry Platforms',
      'Cross-Border HRMS & Talent Infrastructure: India & UAE',
      'Addressable Fire Suppression & Mission-Critical Telemetry',
    ],
  },
  hero: {
    badge: 'DPIIT RECOGNIZED TECH ENTERPRISE',
    heading: 'Designing Secure, Modern & Digital Enterprise Ecosystems.',
    description: 'UniSpark helps enterprises in India and the UAE unify Infrastructure, Cloud, Cybersecurity, Workplace, AI Video Intelligence and Aviation Operations into one integrated, resilient digital foundation.',
    primaryBtnText: 'Explore Capabilities',
    primaryBtnLink: '/capabilities',
    secondaryBtnText: 'Explore Industries',
    secondaryBtnLink: '/industries',
    videoUrl: '',
    imageUrl: '',
  },
  section2: {
    badge: 'Who We Are',
    title: 'Architects of Enterprise Security & Smart Infrastructure',
    description1: 'UNISPARK INNOVATION PRIVATE LIMITED is a startup recognized by the Department for Promotion of Industry and Internal Trade (DPIIT), Government of India.',
    description2: 'Founded in 2020 and headquartered in New Delhi with strategic operations in Dubai, UniSpark Innovation delivers comprehensive physical security systems, CCTV video intelligence, access governance, and managed IT services to commercial enterprises, infrastructure projects, and government installations.',
    statNumber: '24+',
    statLabel: 'Years Executive Tech Leadership',
    statNumber2: '99.98%',
    statLabel2: 'System Uptime',
    imageUrl: '',
  },
  divisions: [
    {
      id: 'div_1',
      title: 'Electronic Security & CCTV Systems',
      description: 'AI-powered 4K surveillance, facial recognition access control, automatic number plate recognition (ANPR), and perimeter intrusion detection.',
      icon: 'FaVideo',
      imageUrl: '',
      link: '/capabilities/electronic-security',
      featured: true,
      tag: 'Security & Surveillance',
    },
    {
      id: 'div_2',
      title: 'Command & Control PSIM Software',
      description: 'Unified Physical Security Information Management (PSIM) bridging multi-site telemetry, incident automation, and live IoT sensor feeds.',
      icon: 'FaShieldAlt',
      imageUrl: '',
      link: '/capabilities/command-control-psim',
      featured: true,
      tag: 'PSIM & Automation',
    },
    {
      id: 'div_3',
      title: 'International HR & Global Workforce',
      description: 'Cross-border workforce deployment, payroll compliance, HR advisory, and bespoke HRMS solutions across India and UAE jurisdictions.',
      icon: 'FaUsers',
      imageUrl: '',
      link: '/international/workforce',
      featured: true,
      tag: 'Global Workforce',
    },
    {
      id: 'div_4',
      title: 'Fire Detection & Suppression',
      description: 'Addressable smoke detection systems, clean agent gas suppression, and automated fire pump control integrated into BMS.',
      icon: 'FaFireExtinguisher',
      imageUrl: '',
      link: '/capabilities/fire-safety',
      featured: true,
      tag: 'Safety Infrastructure',
    },
  ],
  industries: [
    {
      id: 'ind_1',
      title: 'Data Centers & Cloud Hubs',
      description: 'Multi-tier biometric mantrap access control, thermal server rack monitoring, and zero-trust physical perimeter defense.',
      imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
      link: '/industries/data-centers',
    },
    {
      id: 'ind_2',
      title: 'Financial & Banking Institutions',
      description: 'High-security vault access, ATM biometric telemetry, and centralized regional branch monitoring.',
      imageUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?auto=format&fit=crop&w=800&q=80',
      link: '/industries/banking-finance',
    },
    {
      id: 'ind_3',
      title: 'Manufacturing & Industrial Complexes',
      description: 'Hazardous area CCTV, automated workforce attendance, and hazardous gas detection systems.',
      imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
      link: '/industries/manufacturing',
    },
  ],
  whyUs: {
    heading: 'Why Leading Enterprises Choose UniSpark',
    subheading: 'Proven security engineering, government-recognized excellence, and end-to-end service delivery.',
    ctaBgImage: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1600&q=80',
    pillars: [
      { id: 'p_1', title: '24/7 Central Monitoring', desc: 'Real-time incident response with guaranteed 15-minute SLA dispatch.' },
      { id: 'p_2', title: 'Government & DPIIT Recognized', desc: 'Compliant with national safety standards and enterprise compliance mandates.' },
      { id: 'p_3', title: 'Turnkey International Support', desc: 'Dual-headquarters deployment in New Delhi, India and Dubai, UAE.' },
    ],
  },
};
