export const NAV_LINKS = [
  { name: 'About', path: '/about' },
  {
    name: 'Capabilities',
    path: '/capabilities',
    dropdown: [
      { name: 'CCTV & Video Surveillance', path: '/capabilities/cctv-surveillance', desc: 'AI-powered smart surveillance and HD monitoring' },
      { name: 'Access Control Systems', path: '/capabilities/access-control', desc: 'Biometric, RFID and mobile access governance' },
      { name: 'Intruder Alarm & Detection', path: '/capabilities/intruder-alarm', desc: 'Perimeter intrusion detection & alarms' },
      { name: 'Fire Alarm & Safety', path: '/capabilities/fire-alarm', desc: 'Compliant fire detection and evacuation systems' },
      { name: 'Biometric & Smart Security', path: '/capabilities/biometric-security', desc: 'Facial recognition & biometric identity verification' },
      { name: 'Video Intercom & Entry', path: '/capabilities/intercom-door-entry', desc: 'Audio/video intercom & gate barriers' },
      { name: 'Perimeter Security', path: '/capabilities/perimeter-security', desc: 'Advanced perimeter sensors & boundary fences' },
      { name: 'Maintenance Contracts (AMC)', path: '/capabilities/maintenance-contracts', desc: 'SLA-governed 24/7 maintenance & support' },
      { name: 'System Integration & Control', path: '/capabilities/system-integration', desc: 'PSIM, unified control room & NOC design' },
    ],
  },
  {
    name: 'Industries',
    path: '/industries',
    dropdown: [
      { name: 'Aviation & Transportation', path: '/industries/aviation' },
      { name: 'Real Estate & Commercial', path: '/industries/real-estate' },
      { name: 'Oil & Gas / Energy', path: '/industries/oil-gas' },
      { name: 'Hospitality & Leisure', path: '/industries/hospitality' },
      { name: 'Healthcare & Life Sciences', path: '/industries/healthcare' },
      { name: 'Retail & Consumer Goods', path: '/industries/retail' },
      { name: 'BFSI & Banking', path: '/industries/bfsi' },
      { name: 'Manufacturing & Logistics', path: '/industries/manufacturing' },
    ],
  },
  {
    name: 'International',
    path: '/international',
    dropdown: [
      { name: 'Technology & Security', path: '/international/technology-security' },
      { name: 'Workforce Solutions', path: '/international/workforce' },
      { name: 'Security Infrastructure', path: '/international/security-infrastructure' },
      { name: 'HR Solutions', path: '/international/hr-solutions' },
      { name: 'HR Advisory', path: '/international/hr-advisory' },
      { name: 'Payroll & Compliance', path: '/international/payroll-compliance' },
      { name: 'HRMS Platform', path: '/international/hrms' },
      { name: 'Workforce Deployment', path: '/international/workforce-deployment' },
    ],
  },
];

export const CAPABILITIES = [
  {
    id: 'cctv-surveillance',
    title: 'CCTV & Video Surveillance',
    slug: 'cctv-surveillance',
    icon: 'FaVideo',
    desc: 'HD cameras, NVRs, remote monitoring, and smart video analytics for complete site visibility and threat prevention.',
    badge: 'Video Intelligence',
    features: ['High-definition 4K Cameras', 'AI Video Analytics & ANPR', 'Thermal Imaging Solutions', 'Cloud & On-Premise NVR Storage', '24/7 Control Room Integration'],
  },
  {
    id: 'access-control',
    title: 'Access Control Systems',
    slug: 'access-control',
    icon: 'FaFingerprint',
    desc: 'Card, mobile, and biometric physical access control solutions that govern every critical entry and exit point.',
    badge: 'Identity Governance',
    features: ['Multi-Factor Authentication', 'Biometric & Facial Scanners', 'Visitor Management System', 'Elevator & Gate Integration', 'Comprehensive Audit Logs'],
  },
  {
    id: 'intruder-alarm',
    title: 'Intruder Alarm & Detection',
    slug: 'intruder-alarm',
    icon: 'FaExclamationTriangle',
    desc: 'Perimeter and interior intrusion detection with rapid central-station alerting and automated lockdown response.',
    badge: 'Threat Response',
    features: ['Motion & Glass Break Sensors', 'Dual-Tech Infrared Detectors', 'Central Monitoring Alarm Link', 'Mobile Instant Notifications', 'Fail-Safe Battery Backup'],
  },
  {
    id: 'fire-alarm',
    title: 'Fire Alarm & Safety Systems',
    slug: 'fire-alarm',
    icon: 'FaFireExtinguisher',
    desc: 'Compliant fire detection, heat sensors, smoke alarms, and voice evacuation systems for enterprise safety.',
    badge: 'Life Safety',
    features: ['Addressable Fire Alarm Panels', 'Optical & Thermal Detectors', 'Emergency Voice Evacuation', 'Automated Suppression Interface', 'UAE Civil Defence Aligned'],
  },
  {
    id: 'biometric-security',
    title: 'Biometric & Smart Security',
    slug: 'biometric-security',
    icon: 'FaIdCard',
    desc: 'Fingerprint, facial recognition, and smart-card identity verification systems integrated with HR attendance.',
    badge: 'Smart Authentication',
    features: ['Touchless Contactless Face ID', 'Fingerprint Attendance Integration', 'Anti-Spoofing AI Recognition', 'High Throughput Gate Access', 'Cloud Multi-Site Management'],
  },
  {
    id: 'intercom-door-entry',
    title: 'Video Intercom & Door Entry',
    slug: 'intercom-door-entry',
    icon: 'FaPhoneVolume',
    desc: 'Audio/video intercom and door-entry systems for residential towers, commercial offices, and gated campuses.',
    badge: 'Entry Communication',
    features: ['IP Video Door Stations', 'Mobile App Remote Unlock', 'SIP Intercom Protocol Support', 'Vandal-Resistant Hardware', 'Multi-Tenant Concierge Units'],
  },
  {
    id: 'perimeter-security',
    title: 'Perimeter Security & Fencing',
    slug: 'perimeter-security',
    icon: 'FaShieldAlt',
    desc: 'Advanced perimeter intrusion detection, fiber optic fence sensors, and automated bollard barrier integration.',
    badge: 'Boundary Defense',
    features: ['Fiber Optic Fence Cable Sensors', 'Long-Range Infrared Beams', 'Hydraulic Crash Bollards', 'Radar Ground Surveillance', 'PTZ Auto-Tracking Camera Link'],
  },
  {
    id: 'maintenance-contracts',
    title: 'Maintenance Contracts (AMC & PMC)',
    slug: 'maintenance-contracts',
    icon: 'FaWrench',
    desc: 'SLA-governed annual maintenance and preventive maintenance contracts ensuring 99.9% system uptime.',
    badge: 'SLA Uptime',
    features: ['24/7 On-Call Technical Support', 'Preventive Inspection Schedules', 'Spare Parts Warranty Pool', 'Dedicated On-Site Engineers', 'Quarterly Health Audits'],
  },
  {
    id: 'system-integration',
    title: 'System Integration & Control Rooms',
    slug: 'system-integration',
    icon: 'FaProjectDiagram',
    desc: 'Unified security management platforms (PSIM), video wall consoles, and centralized command control room design.',
    badge: 'Enterprise Architecture',
    features: ['PSIM Software Integration', 'Custom Video Wall Displays', 'NOC / SOC Room Ergonomics', 'Unified Event Correlation', 'Third-Party API Bridges'],
  },
];

export const INDUSTRIES = [
  {
    id: 'aviation',
    title: 'Aviation & Transportation',
    slug: 'aviation',
    icon: 'FaPlane',
    desc: 'High-security perimeter control, passenger screening integration, and airfield video analytics.',
  },
  {
    id: 'real-estate',
    title: 'Real Estate & Commercial',
    slug: 'real-estate',
    icon: 'FaBuilding',
    desc: 'Smart building access control, tenant video door entry, visitor kiosks, and automated parking.',
  },
  {
    id: 'oil-gas',
    title: 'Oil & Gas / Energy',
    slug: 'oil-gas',
    icon: 'FaIndustry',
    desc: 'Explosion-proof cameras, thermal gas detection, and long-range perimeter perimeter defense.',
  },
  {
    id: 'hospitality',
    title: 'Hospitality & Leisure',
    slug: 'hospitality',
    icon: 'FaHotel',
    desc: 'Discreet hotel surveillance, keyless guestroom lock systems, and ballroom AV control.',
  },
  {
    id: 'healthcare',
    title: 'Healthcare & Life Sciences',
    slug: 'healthcare',
    icon: 'FaHospital',
    desc: 'Infant protection alarms, pharmacy restricted access control, and cleanroom surveillance.',
  },
  {
    id: 'retail',
    title: 'Retail & Consumer Goods',
    slug: 'retail',
    icon: 'FaShoppingCart',
    desc: 'Loss prevention AI, heat mapping analytics, and POS integrated CCTV surveillance.',
  },
  {
    id: 'bfsi',
    title: 'BFSI & Banking',
    slug: 'bfsi',
    icon: 'FaCoins',
    desc: 'Vault intrusion security, ATM surveillance with panic triggers, and dual-custody access.',
  },
  {
    id: 'manufacturing',
    title: 'Manufacturing & Logistics',
    slug: 'manufacturing',
    icon: 'FaWarehouse',
    desc: 'Warehouse asset tracking, automated vehicle barrier gates, and factory floor monitoring.',
  },
];

export const STATS = [
  { value: '$100M+', label: 'Project Value Delivered' },
  { value: '99.9%', label: 'SLA Support Uptime' },
  { value: '500+', label: 'Enterprise Clients' },
  { value: '24/7', label: 'Command Support NOC' },
];

export const TESTIMONIALS = [
  {
    quote: "UniSpark Innovation transformed our enterprise security infrastructure across 12 commercial sites seamlessly. Their SLA response and technical precision are exceptional.",
    author: "Rajesh Malhotra",
    title: "Chief Operating Officer",
    company: "Apex Global Holdings",
  },
  {
    quote: "The AI Video Intelligence and biometric access controls implemented by UniSpark reduced security incidents by over 75% in our logistics parks.",
    author: "Sultan Al-Mansoori",
    title: "Head of Infrastructure",
    company: "Emirates Logistics Group",
  },
  {
    quote: "Their team's deep expertise in system integration and 24/7 control room design made our digital transformation journey smooth and cost-effective.",
    author: "Priya Sharma",
    title: "VP Technology",
    company: "Nexus Financial Services",
  },
];

export const PARTNERS = [
  { name: 'Hanwha Techwin', category: 'CCTV & Analytics' },
  { name: 'Siemens Security', category: 'Access & Building Automation' },
  { name: 'Honeywell Security', category: 'Fire & Intrusion Alarms' },
  { name: 'Gallagher', category: 'Access Control & Perimeter' },
  { name: 'LenelS2', category: 'Enterprise Security Systems' },
  { name: 'Hochiki', category: 'Life Safety & Fire Detection' },
  { name: 'Bosch Security', category: 'Video & Public Address' },
  { name: 'Hikvision', category: 'Smart Surveillance' },
  { name: 'Dahua Technology', category: 'Video Solutions' },
  { name: 'Fermax', category: 'Video Intercom' },
];
